### PR TITLE
slot-ctrl: remove two lines of unsafe

### PR DESCRIPTION
**Pull request by TheButlah**

### CODE REVIEW

**Review by fouge — COMMENTED** [review]
is it really worth it? 🤔 
it delegates the unsafe code to a third party crate but should we trust libc or rustix more?

**Comment by vmenge** [comment]
> is it really worth it? 🤔 it delegates the unsafe code to a third party crate but should we trust libc or rustix more?

Using `libc` like this causes issues on macOS :/

**Review by vmenge — APPROVED** [review]
LGTM! Did you test it on an orb?

**Comment by TheButlah** [comment]
> is it really worth it?

Yes, long term I want to try to use rustix as much as possible.

I will eventually rewrite the Ioctl stuff using it. It provides good tools for Ioctl calls. See for example my PR to nusb: https://github.com/kevinmehall/nusb/pull/65

**Comment by TheButlah** [comment]
> Did you test it on an orb?

No, because the thing is the same function. But I can do that before merging.

**Comment by fouge** [comment]
@TheButlah let's resolve the conflicts and merge

**Pull request merged**
