### PR TITLE
orb-ui: diamond: self-serve with cone support

### PR DESCRIPTION
**Pull request by fouge**
UX with cone in Diamond self-serve mode.

fixes ORBP-113

### CODE REVIEW

**Comment by TheButlah** [comment]
@fouge shall we rebase on main and mark as ready for review?

**Comment by fouge** [comment]
@TheButlah no, not yet

**Comment by fouge** [comment]
@TheButlah i'm gonna have a look today

**Comment by TheButlah** [comment]
still relevant?

**Comment by fouge** [comment]
closing for now
will reopen when needed

**Pull request closed without merging**
